version: '3.8'

services:
  api:
    image: pariansh/testServer
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "2123:2123"
    volumes:
      - "/home/Pariansh/frontend:/app/uploads"
    restart: always